name: love
description: "A new Flutter project."
publish_to: "none"
version: 1.2.2+5

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.1
  gap: ^3.0.1
  get: ^4.7.2
  get_storage: ^2.1.1
  loading_animation_widget: ^1.3.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  share_plus: ^12.0.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  url_launcher: ^6.3.2
  zoom_tap_animation: ^1.1.0
  flutter_inappwebview: ^6.1.5
  path_provider: ^2.1.5
  another_xlider: ^3.0.2
  intl: ^0.20.2
  firebase_messaging: ^15.1.6
  firebase_core: ^3.8.1
  flutter_local_notifications: ^18.0.1
  google_api_availability: ^5.0.1
  http: ^1.6.0
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/fonts/webfonts/
    - assets/svgs/
    - assets/svgs/fill/
    - assets/db/
    - assets/web/js/
    - assets/web/css/
    - assets/web/html/

  fonts:
    - family: dijlah
      fonts:
        - asset: ./assets/fonts/dijlah-reg.ttf
        - asset: ./assets/fonts/dijfont-bold.ttf
          weight: 700
    - family: SegoeUI
      fonts:
        - asset: ./assets/fonts/SegoeUI.ttf
        - asset: ./assets/fonts/SegoeUI-Semilight.ttf
          weight: 700
    - family: abo
      fonts:
        - asset: assets/fonts/abo.ttf
